### ISSUE TITLE
the .jl are interpreted as lisp files... how to enforce julia interpretation?

### ISSUE THREAD

**Issue by vsilv** [JuliaEditorSupport/julia-vim#64] opened 2015-12-14 00:25 UTC
Maybe someone may tell me how to change this strange behavior. Up to now I am using set :setf julia, but this is not a longterm solution...

**Comment by danielarndt** [comment] 2015-12-15 13:50
Hmm... what version of vim are you using? you could try taking this statement out of the "if" block to see if it fixes it?

https://github.com/JuliaLang/julia-vim/blob/master/ftdetect/julia.vim#L5

In any case, this block seems to be trying to solve this issue...

**Comment by vsilv** [comment] 2015-12-15 15:16
My vim version is 7.4, so this should not be the problem. Anyway, the 

    autocmd BufRead,BufNewFile *.jl set filetype=julia

seems to work. Thank you!

**Comment by danielarndt** [comment] 2015-12-15 15:22
What does `echo v:version` output?

**Comment by vsilv** [comment] 2015-12-15 15:23
704

**Comment by carlobaldassi** [comment] 2015-12-16 23:47
This seems to indicate an incorrect installation of the plugin.
@vsilv did you see issues #10 and #38? Probably something similar is happening with your setup.
If the suggestions in those issues do not fix the problem, please report again here including your OS version, which plugin manager you're using, your .vimrc (or even better a minimal version of it which reproduces the problem) etc., and we'll try to fix it.

**Comment by ExpandingMan** [comment] 2016-07-20 19:27
I was encountering this same issue, adding this line fixed it for me as well.

For future reference I am using vim 7.4 on Ubuntu 16.04.  I encountered this same problem on three different machines with basically the same setup.  The install was done with pathogen, I made no further modifications after cloning the repository.

**Comment by carlobaldassi** [comment] 2017-08-29 21:40
I'm closing this for lack of meaningful activity in quite some time. If the problem comes up again we can reopen.

**Closed by carlobaldassi** 2017-08-29 21:40 UTC
