### ISSUE TITLE
÷ (\div) is treated as part of a word 

### ISSUE THREAD

**Issue by ngphuoc** [JuliaEditorSupport/julia-vim#193] opened 2020-04-30 00:57 UTC
Currently `÷` is treated as part of the word, e.g. `a÷2` is the whole word itself instead of 3 words `a ÷ 2` in vim. Composition operator `∘` works as expected, e.g. `f∘g` are 3 different entities in vim.

**Comment by carlobaldassi** [comment] 2020-04-30 11:24
Since highlighting seems to work fine, I suppose you mean in motions and text objects, e.g. if you do `dw` or `daw`? If that's the issue, then the problem is with vim itself, it's the same issue as in #178.
I'll close this issue as duplicate, but if this is not the case please specify it here and I'll reopen.

**Closed by carlobaldassi** 2020-04-30 11:24 UTC
